services:
  jupyter:
    image: jupyter/base-notebook
    container_name: mlflow-lab
    user: root   # important for passwordless sudo to be applied
    ports:
      - "8848:8888"
    volumes:
      - ./src:/home/jovyan/work
      - ./mlflow_data:/mlflow 
    environment:
      NB_UID: ${DUID}
      NB_GID: ${GID}
      GRANT_SUDO: "yes"
      JUPYTER_TOKEN: mlflow
      JUPYTER_ENABLE_LAB: "yes"
    shm_size: "8g"
    

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/mlflow   # full /mlflow mount
    environment:
      MLFLOW_BACKEND_STORE_URI: sqlite:///mlflow.db
      MLFLOW_ARTIFACT_ROOT: /mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow
      --host 0.0.0.0
      --port 5000
    
